export const categories: Category[] = [
  { name: 'All', image: 'all.jpg' },
  { name: 'Burger', image: 'burgers.jpg' },
  { name: 'Pizza', image: 'pizzas.jpg' },
  { name: 'Pasta', image: 'pastas.jpg' },
  { name: 'Salad', image: 'salads.jpg' },
  { name: 'Dessert', image: 'desserts.jpg' }
]

export const deliveryOptions: DeliveryOption[] = [
  { name: 'Delivery' },
  { name: 'Dine in' },
  { name: 'Take Away' }
]

export const items: Item[] = [
  { name: 'Cheese Burger', category: categories[1], price: 5.99, image: 'cheeseburger.jpg' },
  { name: 'Veggie Burger', category: categories[1], price: 4.99, image: 'veggieburger.jpg' },
  { name: 'Chicken Burger', category: categories[1], price: 6.99, image: 'chickenburger.jpg' },
  { name: 'Pepperoni Pizza', category: categories[2], price: 7.99, image: 'pepperonipizza.jpg' },
  { name: 'Margherita Pizza', category: categories[2], price: 6.99, image: 'margheritapizza.jpg' },
  {
    name: 'Spaghetti Carbonara',
    category: categories[3],
    price: 8.99,
    image: 'spaghetticarbonara.jpg'
  },
  { name: 'Penne Arrabiata', category: categories[3], price: 7.99, image: 'pennearrabiata.jpg' },
  {
    name: 'Fettuccine Alfredo',
    category: categories[3],
    price: 9.99,
    image: 'fettuccinealfredo.jpg'
  },
  { name: 'Caesar Salad', category: categories[4], price: 6.99, image: 'caesarsalad.jpg' },
  { name: 'Greek Salad', category: categories[4], price: 5.99, image: 'greeksalad.jpg' },
  { name: 'Cobb Salad', category: categories[4], price: 7.99, image: 'cobbsalad.jpg' },
  { name: 'Chocolate Cake', category: categories[5], price: 4.49, image: 'chocolatecake.jpg' },
  { name: 'Cheesecake', category: categories[5], price: 4.99, image: 'cheesecake.jpg' },
  { name: 'Tiramisu', category: categories[5], price: 5.49, image: 'tiramisu.jpg' },
  { name: 'Bacon Burger', category: categories[1], price: 6.49, image: 'baconburger.jpg' },
  { name: 'Hawaiian Pizza', category: categories[2], price: 7.49, image: 'hawaiianpizza.jpg' },
  { name: 'Lasagna', category: categories[3], price: 8.49, image: 'lasagna.jpg' },
  { name: 'Nicoise Salad', category: categories[4], price: 6.49, image: 'nicoisesalad.jpg' },
  { name: 'Apple Pie', category: categories[5], price: 4.99, image: 'applepie.jpg' },
  { name: 'Fish Burger', category: categories[1], price: 6.99, image: 'fishburger.jpg' },
  { name: 'BBQ Chicken Pizza', category: categories[2], price: 8.99, image: 'bbqchickenpizza.jpg' },
  {
    name: 'Spaghetti Bolognese',
    category: categories[3],
    price: 8.99,
    image: 'spaghettibolognese.jpg'
  },
  { name: 'Caprese Salad', category: categories[4], price: 6.99, image: 'capresesalad.jpg' },
  { name: 'Lemon Tart', category: categories[5], price: 4.99, image: 'lemontart.jpg' }
]

export const countryList = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas (the)',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia (Plurinational State of)',
  'Bonaire, Sint Eustatius and Saba',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory (the)',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cayman Islands (the)',
  'Central African Republic (the)',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos (Keeling) Islands (the)',
  'Colombia',
  'Comoros (the)',
  'Congo (the Democratic Republic of the)',
  'Congo (the)',
  'Cook Islands (the)',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Curaçao',
  'Cyprus',
  'Czechia',
  "Côte d'Ivoire",
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic (the)',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Falkland Islands (the) [Malvinas]',
  'Faroe Islands (the)',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories (the)',
  'Gabon',
  'Gambia (the)',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and McDonald Islands',
  'Holy See (the)',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran (Islamic Republic of)',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  "Korea (the Democratic People's Republic of)",
  'Korea (the Republic of)',
  'Kuwait',
  'Kyrgyzstan',
  "Lao People's Democratic Republic (the)",
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands (the)',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia (Federated States of)',
  'Moldova (the Republic of)',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands (the)',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger (the)',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands (the)',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine, State of',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines (the)',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Republic of North Macedonia',
  'Romania',
  'Russian Federation (the)',
  'Rwanda',
  'Réunion',
  'Saint Barthélemy',
  'Saint Helena, Ascension and Tristan da Cunha',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin (French part)',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten (Dutch part)',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia and the South Sandwich Islands',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan (the)',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan',
  'Tajikistan',
  'Tanzania, United Republic of',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands (the)',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates (the)',
  'United Kingdom of Great Britain and Northern Ireland (the)',
  'United States Minor Outlying Islands (the)',
  'United States of America (the)',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela (Bolivarian Republic of)',
  'Viet Nam',
  'Virgin Islands (British)',
  'Virgin Islands (U.S.)',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  'Åland Islands'
]
